apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.18.0
networking:
  podSubnet: "10.244.0.0/16" # --pod-network-cidr for flannel
controllerManager:
  extraArgs:
    horizontal-pod-autoscaler-downscale-stabilization: 15s