apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shap-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ray-worker
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50