name: shap
dependencies:
  - python=3.7.4
  - pip
  - pip:
    - numpy
    - pandas
    - shap
    - dask
    - prefect
    - ray
    - scikit-learn
    - matplotlib
    - more_itertools
    - pickle5